
Pre-computed Eleven Lens assessments for demo prospects.

Used in mock mode (no API key) to show Rene what the tool produces.
Each assessment is calibrated based on careful reading of public material
on the prospect.

In live mode, these are generated by Claude API in real time.
"""

from .model import (
    ProspectAssessment, TraitScore, PatternMatch, RedFlag,
    Verdict, Confidence, calculate_overall_confidence,
)


# =============================================================================
# Demo Prospect 1: Stefan Radov (nFuse) — Multi-founder team
# =============================================================================

STEFAN_RADOV_NFUSE = ProspectAssessment(
    prospect_name="Stefan Radov & Stoyan Ivanov",
    company="nFuse",
    is_team=True,
    trait_scores=[
        TraitScore(
            trait_key="problem_obsession",
            score=9,
            justification=(
                "Both founders spent 30+ combined years inside FMCG at Coca-Cola "
                "before disrupting the exact category — domain depth precedes solution."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="radical_honesty",
            score=7,
            justification=(
                "Public metrics shared cleanly (70% adoption vs 15% baseline, €50M "
                "orders processed) but limited public articulation of weaknesses or "
                "what is not yet working."
            ),
            confidence=Confidence.MEDIUM,
        ),
        TraitScore(
            trait_key="resilience_humility",
            score=8,
            justification=(
                "Announcement post explicitly credits co-founder, three investors, "
                "brands, and team — no solo-hero narrative; gratitude framing over "
                "credit-grabbing."
            ),
            confidence=Confidence.MEDIUM,
        ),
        TraitScore(
            trait_key="capital_efficiency",
            score=9,
            justification=(
                "Embedded AI agents in existing messaging channels rather than "
                "building a new portal — capital-efficient design choice that "
                "compounds adoption velocity."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="complementary_team",
            score=8,
            justification=(
                "Two senior FMCG operators with parallel 15-year backgrounds at "
                "Coca-Cola, but no public signal on whether the role division is "
                "Hustler/Hacker or two operators sharing one role."
            ),
            confidence=Confidence.MEDIUM,
        ),
    ],
    pattern_matches=[
        PatternMatch(
            benchmark_founder_name="Alexander Tsvetkov",
            similarity_strength="Strong",
            rationale=(
                "Both are industry veterans using deep legacy domain experience to "
                "disrupt their own sector from inside. The Coca-Cola-to-FMCG-disruption "
                "arc directly mirrors Tsvetkov's insurance-industry-to-Boleron pattern."
            ),
        ),
        PatternMatch(
            benchmark_founder_name="Hristo Borisov",
            similarity_strength="Moderate",
            rationale=(
                "Capital-efficient design choice (AI in existing channels) and the "
                "global ambition implied by FMCG fragmented trade scope echo Borisov's "
                "scale-from-day-one posture, though without yet the demonstrated "
                "international expansion."
            ),
        ),
    ],
    red_flags=[
        RedFlag(
            category="Behavioral",
            description=(
                "Limited public articulation of weaknesses or open problems — "
                "radical honesty is inferred, not directly demonstrated."
            ),
            severity="Watch",
        ),
        RedFlag(
            category="Business",
            description=(
                "70% adoption rate is striking but unverified beyond founder claim "
                "in announcement post. Magnitude warrants independent validation."
            ),
            severity="Watch",
        ),
    ],
    verdict=Verdict.INVESTMENT_READY,
    strategic_recommendation=(
        "Strong fit for Eleven's Future of Work and AI-native investment thesis. "
        "The operator-founder profile (senior Coca-Cola veterans disrupting their own "
        "industry) is exactly the 'bootstrap donkey' pattern Eleven prizes — "
        "capital-efficient, domain-credible, execution-first. Recommend proceeding "
        "with verify questions focused on independent validation of the 70% adoption "
        "metric and direct probe on co-founder role division."
    ),
    sources_analyzed=[
        "Stefan Radov LinkedIn announcement post (April 2026)",
        "Eleven Ventures investment announcement (April 7, 2026)",
        "Rene Tomova reshare commentary",
        "Press coverage: Associated Press, Financial Times, Business Insider",
    ],
    overall_confidence=Confidence.MEDIUM,
)


# =============================================================================
# Demo Prospect 2: Nikola Lazarov (Eilla AI) — Solo CEO
# =============================================================================

NIKOLA_LAZAROV_EILLA = ProspectAssessment(
    prospect_name="Nikola Lazarov",
    company="Eilla AI",
    is_team=False,  # Treated as solo CEO for this assessment
    trait_scores=[
        TraitScore(
            trait_key="problem_obsession",
            score=10,
            justification=(
                "Spent 3 years selling AI tools to investment banks before realizing "
                "the work itself was the product — problem obsession at the level of "
                "killing existing revenue to bet on a deeper insight."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="radical_honesty",
            score=9,
            justification=(
                "Public post explicitly admits the original 3-year SaaS thesis was "
                "wrong: 'we shouldn't be selling tools to advisors. We should be the "
                "advisor.'"
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="resilience_humility",
            score=8,
            justification=(
                "Frames pivot as 'we realised' (collective) not 'I figured out' "
                "(heroic); explicitly credits Eleven partner Svetozar Georgiev's "
                "strategic guidance during the pivot."
            ),
            confidence=Confidence.MEDIUM,
        ),
        TraitScore(
            trait_key="capital_efficiency",
            score=10,
            justification=(
                "Success-fee-only model is the ultimate capital-efficient design — "
                "unit economics work only because AI compresses cost-to-serve by an "
                "order of magnitude versus traditional advisory."
            ),
            confidence=Confidence.HIGH,
        ),
    ],
    pattern_matches=[
        PatternMatch(
            benchmark_founder_name="Ivan Osmak",
            similarity_strength="Strong",
            rationale=(
                "Both founders make global ambition an early decision rather than a "
                "later milestone. Eilla AI's first deal is a cross-border CEE-to-Sweden "
                "M&A transaction — the same global-from-day-one posture that defined "
                "Quantive's US enterprise push."
            ),
        ),
        PatternMatch(
            benchmark_founder_name="Hristo Borisov",
            similarity_strength="Moderate",
            rationale=(
                "Like Borisov, Lazarov is comfortable selling sophisticated SaaS-"
                "adjacent products into demanding enterprise buyers. The communication "
                "discipline (hard numerics, sharp positioning) matches the Payhawk "
                "scale-up profile."
            ),
        ),
    ],
    red_flags=[
        RedFlag(
            category="Business",
            description=(
                "15-day timeline on first deal could be selection bias on a "
                "particularly clean transaction; repeatability across the 20-mandate "
                "pipeline unverified."
            ),
            severity="Watch",
        ),
    ],
    verdict=Verdict.INVESTMENT_READY,
    strategic_recommendation=(
        "Exceptional fit for Eleven's AI-native investment thesis and Future of Work "
        "vertical. The pivot history is the cleanest possible Strategic Flexibility "
        "signal — most founders cannot demonstrate this until their first crisis, "
        "but Lazarov has executed and articulated the lesson cleanly. Already absorbing "
        "platform value from Svetozar's strategic guidance. Recommend continued "
        "portfolio intensity and consideration for follow-on participation."
    ),
    sources_analyzed=[
        "Nikola Lazarov LinkedIn announcement post (April 2026)",
        "Rene Tomova reshare commentary",
        "Public deal coverage: White Pearl Technology Group acquisition",
        "Eleven Ventures partner statements",
    ],
    overall_confidence=Confidence.HIGH,
)


# =============================================================================
# Demo Prospect 3: A weaker example — illustrates what failure looks like
# =============================================================================
# Including a deliberately weak fictional prospect lets Rene see the full
# range of Eleven Lens output, not just the optimistic end.

FICTIONAL_WEAK_PROSPECT = ProspectAssessment(
    prospect_name="[Demo: Weak Profile Example]",
    company="[Fictional B2B AI Startup]",
    is_team=False,
    trait_scores=[
        TraitScore(
            trait_key="problem_obsession",
            score=4,
            justification=(
                "Pitch leads with technology architecture and competitor differentiation; "
                "customer problem articulated only at high level without specific pain points."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="radical_honesty",
            score=3,
            justification=(
                "Selectively presents favorable metrics; deflects direct questions on "
                "current revenue and burn rate by referring to 'pipeline' figures."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="resilience_humility",
            score=5,
            justification=(
                "Solo-founder narrative dominates; past failures mentioned only as "
                "external circumstances rather than internal lessons; defensive on "
                "feedback about TAM assumption."
            ),
            confidence=Confidence.MEDIUM,
        ),
        TraitScore(
            trait_key="capital_efficiency",
            score=3,
            justification=(
                "Burn plan assumes 15-person hire in first 12 months; no articulation "
                "of AI-native unit economics or revenue per FTE benchmark."
            ),
            confidence=Confidence.HIGH,
        ),
    ],
    pattern_matches=[
        PatternMatch(
            benchmark_founder_name="Volen Vulkov",
            similarity_strength="Loose",
            rationale=(
                "Surface-level similarity in product category (consumer-facing AI tool), "
                "but missing Vulkov's PLG discipline and obsessive UX iteration. Loose "
                "industry match, not a behavioral one."
            ),
        ),
    ],
    red_flags=[
        RedFlag(
            category="Behavioral",
            description=(
                "Defensive responses to direct numerical questions in pitch — sugarcoats "
                "current revenue by pointing to pipeline; deflects on burn rate."
            ),
            severity="Concern",
        ),
        RedFlag(
            category="Behavioral",
            description=(
                "Solo-hero narrative throughout pitch; team mentioned generically; "
                "no public credit-giving to mentors or advisors.",
            ),
            severity="Watch",
        ),
        RedFlag(
            category="Business",
            description=(
                "15-person hire plan in 12 months on seed round contradicts capital "
                "efficiency — burn assumes platform-style scale before revenue validation."
            ),
            severity="Concern",
        ),
    ],
    verdict=Verdict.PASS,
    strategic_recommendation=(
        "Fundamental mismatch with Eleven's evaluation thesis. Capital efficiency and "
        "radical honesty signals are weak in directions that platform support cannot "
        "compensate for. Recommend pass and feedback to founder on the radical-honesty "
        "behavioral pattern — that gap is the most fixable, but only if the founder "
        "wants to fix it. Worth referring to alternative investors with different theses "
        "if the underlying technology is strong."
    ),
    sources_analyzed=[
        "[Fictional pitch deck excerpt for demonstration]",
        "[Fictional founder interview notes]",
    ],
    overall_confidence=Confidence.HIGH,
)


# =============================================================================
# Demo Prospect 4: Maria Ivanova & Petar Georgiev (sample-form-input)
# =============================================================================
# This sample is referenced by the "Analyze a New Prospect" page when running
# in mock mode. It demonstrates what Eleven Lens output looks like when
# someone pastes the structured form input.

MARIA_PETAR_SAMPLE = ProspectAssessment(
    prospect_name="Maria Ivanova & Petar Georgiev",
    company="[Logistics AI startup — submitted via form]",
    is_team=True,
    trait_scores=[
        TraitScore(
            trait_key="problem_obsession",
            score=8,
            justification=(
                "Maria spent 10 years inside DHL logistics management — domain depth "
                "precedes solution; she has lived the problem before deciding to build."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="radical_honesty",
            score=9,
            justification=(
                "When Rene asked about high CAC, Maria openly admitted they are struggling "
                "and don't have a solution yet — this is textbook radical transparency, not "
                "the deflection-to-pipeline pattern Eleven flags as a red flag."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="resilience_humility",
            score=7,
            justification=(
                "Petar's prior failed startup is potentially a strong asset if lessons "
                "were absorbed; self-taught ML engineering implies persistence; needs "
                "verification of what Petar specifically learned from the failure."
            ),
            confidence=Confidence.MEDIUM,
        ),
        TraitScore(
            trait_key="capital_efficiency",
            score=10,
            justification=(
                "$5,000 of personal savings to a working MVP is the absolute extreme of "
                "capital efficiency — the textbook 'bootstrap donkey' profile Eleven prizes."
            ),
            confidence=Confidence.HIGH,
        ),
        TraitScore(
            trait_key="complementary_team",
            score=8,
            justification=(
                "Maria handled the business narrative while Petar stepped in 'perfectly' on "
                "the data pipeline question — clean Hustler/Hacker role division observed "
                "in the pitch dynamic itself."
            ),
            confidence=Confidence.MEDIUM,
        ),
    ],
    pattern_matches=[
        PatternMatch(
            benchmark_founder_name="Alexander Tsvetkov",
            similarity_strength="Strong",
            rationale=(
                "Both founders use deep legacy industry experience to disrupt their own "
                "sector from inside. The DHL-to-logistics-AI arc directly mirrors "
                "Tsvetkov's insurance-industry-to-Boleron pattern."
            ),
        ),
        PatternMatch(
            benchmark_founder_name="Georgi Petrov",
            similarity_strength="Moderate",
            rationale=(
                "Capital-efficient build pattern ($5K MVP) and the technical-builder + "
                "GTM-operator division of labor echo the SMSBump dynamic, though without "
                "yet the demonstrated commercial traction."
            ),
        ),
    ],
    red_flags=[
        RedFlag(
            category="Behavioral",
            description=(
                "Maria 'dominated the conversation' — needs probing in second meeting to "
                "distinguish healthy leadership from unhealthy founder dynamic. The fact "
                "that Petar stepped in cleanly when needed is positive, but Eleven should "
                "verify the dynamic in unstructured settings."
            ),
            severity="Watch",
        ),
        RedFlag(
            category="Business",
            description=(
                "High CAC with no current solution is a real GTM concern. The radical "
                "honesty about it is positive, but the underlying problem still needs "
                "to be solvable for the business model to work."
            ),
            severity="Concern",
        ),
        RedFlag(
            category="Behavioral",
            description=(
                "Petar's prior failed startup needs explicit lesson-extraction in IC "
                "meeting — past failure is an asset only if learned from."
            ),
            severity="Watch",
        ),
    ],
    verdict=Verdict.INCUBATION_NEEDED,
    strategic_recommendation=(
        "Strong fit for Eleven's incubation thesis — exceptional underlying traits "
        "(radical honesty, capital efficiency, domain depth) but specific GTM problems "
        "the platform team can compound value on. The CAC issue is exactly the kind of "
        "problem Rene's platform model is designed to solve. Recommend deep DD focused "
        "on three verify-questions: (1) what did Petar specifically learn from the failed "
        "startup, (2) is Maria's leadership style coachable on the dominance pattern, "
        "and (3) what is the unit-economic path that makes the CAC tractable. "
        "If those three answers land, this is a Strong Incubation Needed → Investment "
        "Ready trajectory within 90 days."
    ),
    sources_analyzed=[
        "Form input: Founder background (DHL, ML engineering, prior failure)",
        "Form input: Pitch and conversation notes",
        "Form input: Capital efficiency signal ($5K MVP)",
    ],
    overall_confidence=Confidence.MEDIUM,
)


# =============================================================================
# Registry
# =============================================================================

DEMO_PROSPECTS = {
    "stefan_radov_nfuse": STEFAN_RADOV_NFUSE,
    "nikola_lazarov_eilla": NIKOLA_LAZAROV_EILLA,
    "fictional_weak_example": FICTIONAL_WEAK_PROSPECT,
}


# Sample shown when user submits the "Analyze a New Prospect" form in mock mode
FORM_SAMPLE_ASSESSMENT = MARIA_PETAR_SAMPLE
